FROM node:latest
COPY ./ /app
WORKDIR /app
RUN npm install --force
CMD ["npm", "run", "dev"]

# COPY ./package* ./
# COPY ./tsconfig* ./

 
# RUN npm install --include=dev --force && npm install --force
# RUN npm install --force
# RUN npm install
 
# COPY ./ .

# CMD ["npm", "run", "dev"]
# RUN npm run dev

#docker run -it dockernode /bin/bash